# Site settings
title: Great New Blog Title
author:
  name: Jagjeet Rathore
  email: jagjeetrathore@domain.com
description: "Great site about classification on GitHub-Pages."

# Build settings
remote_theme: jekyll/minima

